import pandas as pd
import numpy as np
import pandas_ta as ta # Import pandas-ta
import logging

import config
import utils

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def calculate_technical_indicators(df, indicators_config=config.TECHNICAL_INDICATORS):
    """Calculates technical indicators using pandas-ta."""
    if df is None or df.empty:
        return df

    # Create a copy to avoid modifying the original DataFrame unexpectedly
    df_ta = df.copy()

    # pandas-ta works best with lowercase column names
    df_ta.columns = [col.lower() for col in df_ta.columns]

    # Check if required columns exist
    required_cols = ['open', 'high', 'low', 'close', 'volume']
    if not all(col in df_ta.columns for col in required_cols):
        missing = [col for col in required_cols if col not in df_ta.columns]
        logging.warning(f"DataFrame missing required columns for pandas-ta: {missing}. Skipping TA calculation.")
        # Return the original DataFrame without TA features
        return df # Or return None, or df_ta without indicators

    # Create a pandas-ta strategy
    strategy_indicators = []
    for name, params in indicators_config.items():
        kind = params['kind']
        # Copy params dict and remove 'kind' before passing to ta.Strategy
        indicator_params = params.copy()
        del indicator_params['kind']
        strategy_indicators.append(ta.Indicator(kind, **indicator_params))

    # Create and apply the strategy
    if strategy_indicators:
        strategy = ta.Strategy(
            name="Custom Strategy",
            ta=strategy_indicators
        )
        try:
            # Append indicators to the DataFrame
            df_ta.ta.strategy(strategy, append=True)
            logging.debug(f"Applied pandas-ta strategy. New columns: {df_ta.columns}")
        except Exception as e:
            logging.error(f"Error applying pandas-ta strategy: {e}", exc_info=True)
            # Return original df or df_ta without new indicators? For safety, return original.
            return df

    # Merge the calculated indicators back into the original DataFrame
    # Identify new columns added by pandas-ta
    original_cols = list(df.columns)
    new_cols = [col for col in df_ta.columns if col.lower() not in [c.lower() for c in original_cols]]

    # Create a result DataFrame with original index and columns + new TA columns
    df_result = df.copy()
    for col in new_cols:
        # Ensure column names match expected format (often uppercase start, e.g. SMA_10)
        # pandas-ta usually returns them in a standard format already.
        # We use the names generated by pandas-ta directly.
        df_result[col] = df_ta[col]

    return df_result

# --- Keep the rest of feature_engineer.py the same ---

def add_fundamental_features(df, ticker):
     """Placeholder - No changes needed here"""
     logging.debug(f"Fundamental feature addition skipped/placeholder for {ticker}.")
     return df


def preprocess_data_for_ticker(ticker, macro_data):
    """Loads, adds features, and merges macro data for a single ticker."""
    df = utils.load_data_from_file(ticker)
    if df is None or df.empty:
        logging.warning(f"No data loaded for {ticker}, skipping feature engineering.")
        return None

    # Ensure date index
    if not isinstance(df.index, pd.DatetimeIndex):
         df.index = pd.to_datetime(df.index)

    # Calculate Technical Indicators (Uses the updated function)
    df = calculate_technical_indicators(df) # Pass the DataFrame

    # Add Fundamental Features (Placeholder)
    df = add_fundamental_features(df, ticker)

    # Add Return Features
    # Ensure 'Close' column exists before calculating return
    if 'Close' in df.columns:
        df['log_return'] = np.log(df['Close'] / df['Close'].shift(1))
    else:
        logging.warning(f"'Close' column not found in DataFrame for {ticker} after TA calculation. Cannot compute log_return.")


    # Merge Macro Data
    if macro_data is not None and not macro_data.empty:
         # Ensure macro_data index is datetime
         if not isinstance(macro_data.index, pd.DatetimeIndex):
             macro_data.index = pd.to_datetime(macro_data.index)

         df = pd.merge(df, macro_data, left_index=True, right_index=True, how='left')
         # Forward fill macro data after merging
         macro_cols = macro_data.columns
         # Check if macro columns actually exist in df after merge
         cols_to_fill = [col for col in macro_cols if col in df.columns]
         if cols_to_fill:
              df[cols_to_fill] = df[cols_to_fill].ffill()


    # Drop initial rows with NaNs due to indicator calculations/shifts
    # Be more specific about columns to check for NaNs if needed (e.g., indicator columns)
    # identify indicator columns generated based on config or naming convention
    indicator_cols = []
    temp_df_for_cols = pd.DataFrame(columns=['open', 'high', 'low', 'close', 'volume']) # Dummy df
    temp_df_for_cols.ta.strategy(ta.Strategy(name="temp", ta=[ta.Indicator(p['kind'], **{k:v for k,v in p.items() if k!='kind'}) for p in config.TECHNICAL_INDICATORS.values()]), append=True)
    indicator_cols = [col for col in temp_df_for_cols.columns if col not in ['open', 'high', 'low', 'close', 'volume']]

    nan_check_cols = ['log_return'] + indicator_cols
    # Only check NaNs in cols that actually exist in df
    nan_check_cols = [col for col in nan_check_cols if col in df.columns]
    if nan_check_cols:
        df = df.dropna(subset=nan_check_cols, how='any')
    else:
         logging.warning(f"No specific columns found for NaN check in {ticker}. Applying dropna(how='any') broadly.")
         df = df.dropna(how='any')


    # Ensure required columns (Open, Close) still exist for the environment
    if 'Open' not in df.columns or 'Close' not in df.columns:
         logging.error(f"Required columns 'Open' or 'Close' missing for {ticker} after processing. Check TA function.")
         return None


    return df


def create_feature_dataset(tickers, start_date, end_date):
    """Creates the final feature dataset for all tickers."""
    logging.info("--- Starting Feature Engineering Process ---")
    all_features = {}
    macro_data = utils.load_data_from_file("_macro_data")
    if macro_data is not None:
        macro_data.index = pd.to_datetime(macro_data.index)
        logging.info("Loaded macro data.")


    for ticker in tickers:
        logging.debug(f"Processing features for {ticker}...")
        processed_df = preprocess_data_for_ticker(ticker, macro_data)
        if processed_df is not None and not processed_df.empty:
            # Filter date range AFTER feature calculation to avoid lookahead bias
            processed_df = processed_df.loc[start_date:end_date]
            if not processed_df.empty:
                 all_features[ticker] = processed_df
                 logging.debug(f"Finished features for {ticker}, shape: {processed_df.shape}")
            else:
                 logging.warning(f"No data remaining for {ticker} after date filtering {start_date} to {end_date}.")
        else:
             logging.warning(f"Skipping {ticker} due to processing issues or lack of data.")


    if not all_features:
         logging.error("No features were generated for any ticker. Exiting.")
         return None

    logging.info(f"--- Feature Engineering Completed for {len(all_features)} tickers ---")
    return all_features # Return dictionary


if __name__ == "__main__":
    sp500_tickers = utils.get_sp500_tickers()
    stock_tickers = [t for t in sp500_tickers if t not in config.MACRO_FEATURES.values() and t != config.BENCHMARK_TICKER]

    features_dict = create_feature_dataset(stock_tickers, config.START_DATE, config.END_DATE_TRAIN)

    if features_dict:
        sample_ticker = next(iter(features_dict)) # Get first available ticker
        print(f"\nSample Features for {sample_ticker} (using pandas-ta):")
        print(features_dict[sample_ticker].head())
        print("\nFeatures Summary:")
        # Show shapes and columns of a sample dataframe
        if sample_ticker in features_dict:
             print(f"Shape for {sample_ticker}: {features_dict[sample_ticker].shape}")
             print(f"Columns for {sample_ticker}: {features_dict[sample_ticker].columns.tolist()}")
        # print({k: v.shape for k, v in features_dict.items()}) # Can be long
